# Generated by Django 5.1.4 on 2024-12-10 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_order_address_alter_order_full_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='full_name',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
